### ISSUE TITLE
Blacklisted sites to consider adding

### ISSUE THREAD

**Issue by bauerbach** [grantwinney/hide-comments-everywhere#131] opened 2022-10-26 14:51 UTC
Here's my list of blacklisted sites to consider blocking by default.

```
www\.youtube\.com; #place_your_selectors_here
```

Also, I think YouTube made a change preventing comments on community posts from being blocked.

**Comment by grantwinney** [comment] 2022-11-13 04:00
Duplicate of #133 _(I commented on that one)_

**Closed by grantwinney** 2022-11-13 04:00 UTC
