### ISSUE TITLE
myanimelist and anilist req

### ISSUE THREAD

**Issue by scottbrosnahan** [grantwinney/hide-comments-everywhere#120] opened 2022-08-12 03:03 UTC
Here's a new site I'd like you to consider blocking. (include as many details as possible)

https://anilist.co/
https://myanimelist.net/
hide reviews and comments not working

**Comment by grantwinney** [comment] 2022-08-21 14:22
duplicate of #119

**Closed by grantwinney** 2022-08-21 14:22 UTC
